#! /bin/sh

# Run SXHKD
pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.local/bin/eww -c $HOME/.config/eww/bar --restart open bar &
pgrep -x battery-alert > /dev/null || ~/bin/battery-alert &

# bspc monitor LVDS1 -d 1 2 3 4 5
# bspc monitor VGA1 -d 6 7 8 9 0
bspc monitor -d 1 2 3 4 5 6 7

bspc config left_padding	       50
bspc config border_width         1
bspc config window_gap           7
bspc config focused_border_color "#444b6a"
bspc config normal_border_color  "#32344a"
bspc config active_border_color  "#444b6a"
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Kitty follow=on rectangle=620x390+80+80
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

